# Generated by Django 6.0.1 on 2026-02-05 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='participant',
        ),
        migrations.AddField(
            model_name='studysession',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, related_name='joined_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
