# Generated by Django 6.0.1 on 2026-02-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_studysession_participant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studysession',
            old_name='participant',
            new_name='participants',
        ),
    ]
