# Generated by Django 6.0.1 on 2026-02-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_studysession_participants_usermedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='file_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
